### ISSUE TITLE
Add an option to walk

### ISSUE THREAD

**Issue by bemyak** [xyzz/openmw-android#13]
While playing Morrowind it is usually a good idea to keep your stamina level high, especially on low-level characters.
So, in current version of OpenMW-Android by default your character is always running. The only way to make her walk is to bind "Always Run" option in settings to some letter key and then press it on keyboard while in game. This is not very convenient.

I suggest adding to UI a new button that will behave like Caps Lock - switch between running and walking.

**Comment by xyzz** [comment]
It should already be possible to walk by turning the joystick a little instead of the whole way, can you try that?

**Comment by bemyak** [comment]
Oh, indeed, my bad. Thank you!
