### ISSUE TITLE
Graphics library rendering issue on Oculus quest

### ISSUE THREAD

**Issue by SHMAUS-Carter** [xyzz/openmw-android#14]
Both the GLESv1 and GLESv2 graphics librarys fail to render the world on the Oculus Quest when sideloaded and run via Oculus TV. The world shows up as white. The menus work fine though.

**Comment by xyzz** [comment]
Are there any messages in logcat? I'm afraid I can't do much about this since I don't own the oculus.

**Comment by SHMAUS-Carter** [comment]
How do you check logcat been a while since I have messed with logcat.

**Comment by terabyte25** [comment]
> adb logcat

**Comment by SHMAUS-Carter** [comment]
[ 06-28 23:55:03.622  1768: 1768 I/OVRPlatform ]
[PartiesAPI] ovr_Party_PluginGetSharedMemHandle: This function is deprecated, do not use

[ 06-28 23:55:03.635  1768: 1768 E/OVRMediaServiceManager ]
Not initialized

[ 06-28 23:55:03.636  1117: 1526 W/ActivityManager ]
Finishing task with all activities already finished

[ 06-28 23:55:03.637  1117: 1526 W/ActivityManager ]
Duplicate finish request for ActivityRecord{e4c17e u0 is.xyz.omw/ui.activity.GameActivity t251 f}

[ 06-28 23:55:03.637 26056:26056 I/Process  ]
Sending signal. PID: 26056 SIG: 9

[ 06-28 23:55:03.677  1117:25252 W/InputMethodManagerService ]
Focus gain on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@dfa6e87 (uid=10102 pid=25032)

[ 06-28 23:55:03.719  1768: 1768 I/PlatformPluginManager ]
enforcePartyChatStateConsistency - User not in a party.

[ 06-28 23:55:03.719  1768: 1768 I/PlatformPluginManager ]
stopPartyChat

[ 06-28 23:55:03.719  1768: 1768 I/PlatformPlugin ]
[PlatformPluginManager] Stopping party chat

[ 06-28 23:55:03.748   710:25983 I/[CT]     ]
MANAGEMENT:CONSTELLATION: Status=GREEN,, Obj=16786689372854406953,6DOF=1,FusJit=0.004mm,Issues(Cam/min=  0,IMU/min=0), Obj=9944492763118622970,6DOF=1,FusJit=0.0mm,Issues(Cam/min=  0,IMU/min=0)

[ 06-28 23:55:03.848  1117: 1887 I/SyncBossHAL ]
internal/syncboss_hal_prox.c(38): INFO: Reporting prox event: prox_off

[ 06-28 23:55:03.848  1117: 1191 D/SensorsHAL ]
returning 1 events to client

[ 06-28 23:55:03.849  1515: 1515 D/VRPowerManagerService ]
processing message: sensor changed

[ 06-28 23:55:03.850  1515: 1515 I/VRPowerManagerService ]
transition from HEADSET_MOUNTED to HEADSET_UNMOUNTED

[ 06-28 23:55:03.857  1464: 1491 D/VRPowerManagerClient ]
Headset state: 3

[ 06-28 23:55:03.857  1464: 1491 V/ControllerNotifications ]
Handling unmount notification

[ 06-28 23:55:03.858   710:  831 D/TrackingService ]
Received transition request to STANDBY current is RUNNING

[ 06-28 23:55:03.858   710:  831 D/TrackingService ]
Executing transition from RUNNING to STANDBY

[ 06-28 23:55:03.860  2155: 2243 I/ClientMgr ]
Headset was unmounted

[ 06-28 23:55:03.863  1826: 1905 I/VrApi    ]
ovr_HandleHmdEvents: HMT was UNmounted

[ 06-28 23:55:03.868  2155:25996 I/GuardianRenderLayer ]
GuardianRenderLayer: Rendering status changed: false

[ 06-28 23:55:03.870  2155:25996 I/Clocks   ]
SetSchedFifo( tid=1905, pri=0 ) succeeded

[ 06-28 23:55:03.873   547: 1244 D/audio_hw_primary ]
adev_set_mic_mute state 0


[ 06-28 23:55:03.875  1826: 1905 I/[OAR] ShellApp ]
HMD Mount State Changed - unmounted

[ 06-28 23:55:03.875  1826: 1905 I/[OAR] ShellApp ]
Background

[ 06-28 23:55:03.876  1826: 1905 I/[OAR] PanelAppHost ]
OnBackground

[ 06-28 23:55:03.876  1826: 1905 I/[OAR] PanelAppHost ]
Panel app 7 (com.oculus.tv/com.oculus.tv.PanelService) changing state from foreground to background

[ 06-28 23:55:03.876  1826: 1905 D/[OAR] MainActivity ]
notify OS to set com.oculus.tv/com.oculus.tv.PanelService to BACKGROUND

[ 06-28 23:55:03.881  1826: 1905 I/[OAR] PanelAppHost ]
com.oculus.tv/com.oculus.tv.PanelService:7 is now backgrounded due to: hmdDismount

[ 06-28 23:55:03.882 24967:24985 I/RCTVR    ]
AppState background

[ 06-28 23:55:03.884  2155: 2169 I/VrRuntimeService ]
nativeDestroyTextureSwapChain 145

[ 06-28 23:55:03.886  1117: 1195 W/InputDispatcher ]
channel '6f70471 is.xyz.omw/ui.activity.GameActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9

[ 06-28 23:55:03.886  1117: 1195 E/InputDispatcher ]
channel '6f70471 is.xyz.omw/ui.activity.GameActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

[ 06-28 23:55:03.887 24967:24967 D/TVPanelApp ]
onPanelAppVisibilityChanged: foreground=false

[ 06-28 23:55:03.887  1117: 1477 I/WindowManager ]
WIN DEATH: Window{49182ea u0 SurfaceView - is.xyz.omw/ui.activity.GameActivity}

[ 06-28 23:55:03.888  1117:25402 D/GraphicsStats ]
Buffer count: 6

[ 06-28 23:55:03.888  1800: 1811 D/VrDesktopService ]
pauseActivities(): container=android.app.IActivityContainer$Stub$Proxy@db4ac9c

[ 06-28 23:55:03.889  1117: 1486 I/ActivityManager ]
Process is.xyz.omw (pid 26056) has died

[ 06-28 23:55:03.889  1117: 1486 D/ActivityManager ]
cleanUpApplicationRecord -- 26056

[ 06-28 23:55:03.893 24967:25005 I/RCTVR_HERMES ]
[info]: 'Analytics', { section_type: 'Channel',
  section_group: 'partner',
  section_name: 'com.sidequest.launcher',
  party_id: '0',
  party_is_host: false,
  party_size_in_app: 0,
  active_duration_ms: 54723,
  real_timestamp: 1561784103892,
  type: 'section_exit' }

[ 06-28 23:55:03.893  1117: 9504 I/WindowManager ]
WIN DEATH: Window{6f70471 u0 is.xyz.omw/ui.activity.GameActivity}

[ 06-28 23:55:03.893  1117: 9504 W/InputDispatcher ]
Attempted to unregister already unregistered input channel '6f70471 is.xyz.omw/ui.activity.GameActivity (server)'

[ 06-28 23:55:03.903  1768: 2172 W/VRLifecycleSessionManager ]
No apps were active so skipping session.

[ 06-28 23:55:03.904  1768: 2172 W/VRLifecycleManager ]
onHeadsetUnmounted

[ 06-28 23:55:03.924 25032:25032 D/com.sidequest.launcher.gui.MainActivity ]
Update Time stopped

[ 06-28 23:55:03.926  1117: 1501 D/WindowManager ]
Secondary display focus changed from Window{e09e16b u0 com.sidequest.launcher/com.sidequest.launcher.gui.MainActivity} to null

[ 06-28 23:55:03.930  1826: 2331 E/Parcel   ]
Reading a NULL string not supported here.

[ 06-28 23:55:03.931  1826: 2331 D/AudioTrack ]
updateAppOpsPlayAudio: checkOp OP_PLAY_AUDIO for com.oculus.vrshell returns: 0 (ALLOWED)

[ 06-28 23:55:04.048  1768:26018 W/VRLifecycleManager ]
onHeadsetUnmounted

**Comment by SHMAUS-Carter** [comment]
[logcat_omw.txt](https://github.com/xyzz/openmw-android/files/3341403/logcat_omw.txt)

**Comment by tomtastico** [comment]
It works fine for me in the Quest with GLESv2. Water reflections and all. Works exactly as in my phone.

I used the SideQuest TV launcher as I could not found the app at all in Unknown Sources nor Oculus TV. Not sure if that made any difference.

**Comment by SHMAUS-Carter** [comment]
I haven't tried since recent firmware updates maybe they fixed a firmware
issue.

**Comment by SHMAUS-Carter** [comment]
Just tested it again on my quest and it's working just fine. Must have been the firmware version.
