### ISSUE TITLE
Option to move Stealth or other buttons out of the toolbar group (feature)

### ISSUE THREAD

**Issue by billbaggins** [xyzz/openmw-android#17]
Right now in the Stable release, stealth is only visible if the whole toolbar menu is visible.  It looks like it used to be a dedicated touchscreen control but to conserve screen space was moved to the toolbar and replaced with the minimap.

The minimap was a great addition, but having a stealth based character quick access to the stealth button is nice too.

**Comment by xyzz** [comment]
Resolved by a4cf2523dbb3f3119427968bf5f1aaab9090eb82
