### ISSUE TITLE
Build 23 - memory leak with FPS on

### ISSUE THREAD

**Issue by licaon-kter** [xyzz/openmw-android#19]
Local build, arm64, Mate 9 stock Pie

Steps, clean install:
* start app
* allow storage
* select game folder
* enable "enable FN keys"
* start game
* load savegame/new game

Expected:
* press FN -> F3
* game runs
* see framerate

Actual result:
* press FN -> F3
* game runs
* see framerate
* after a while it exits
* see that other apps (eg. Conversations) have been killed and they need to reconnect

Triggered faster with texture mods and more "cells" loaded.

Worked fine on build 22.

**Comment by terabyte25** [comment]
https://gitlab.com/OpenMW/openmw/issues/4985

**Comment by licaon-kter** [comment]
@terabyte25 Not sure it's the name thing, this happens on Vanilla too, also this didn't happen on build 21published on July 01(so it should have that faulty commit, right?), neither Vanilla nor modded.

**Comment by terabyte25** [comment]
I'm not really sure if it's the same bug, maybe it might somehow be related?

**Comment by licaon-kter** [comment]
Triggering it with F4 too, I can see NavMesh cache fill up (and tiles going up to 1000) then crash.

**Comment by xyzz** [comment]
Seems related to this: https://github.com/openscenegraph/OpenSceneGraph/issues/806 which is fixed by https://github.com/openscenegraph/OpenSceneGraph/commit/149c04b0df37e605a94495363801eb518b58a059

**Comment by xyzz** [comment]
e25a1bdd000f96774523bd5730ea1c5c845bcdb7

**Comment by licaon-kter** [comment]
Yup, fixed, thanks
