### ISSUE TITLE
Not finding gamedatas 

### ISSUE THREAD

**Issue by julian70400** [xyzz/openmw-android#20]
Hello,

In the current nightly, gamedatas are not found. 

When I select my folder (which one is working with last release), even if I select the good path, it's not working.
It is searching in "/emulated/0/Morrowind" instead of "/storage/emulated/0/Morrowind" 

Currently using huawei p10. 

Please, add the possibility to force the path, as the release. Select seem to not work properly.

**Comment by licaon-kter** [comment]
You do have Morrowind.INI and Data Files/ folder there, right? No issue here on Mate9 Pie.

**Comment by julian70400** [comment]
"Morrowind.ini" is under /morrowind and "datas" folder is also in the same folder.
And it works like a charm with the release, but I've got this problem only with the nightly build.

**Comment by licaon-kter** [comment]
Pics of the steps? 

This is Nightly from Github or F-Droid? I'm using F-Droid.

**Comment by julian70400** [comment]
OK, it works now.

Problem is coming from the fact my data repository is by default named "datas". If work perfectly with release because we can write ourself the path.

In the nighly one, we have to select the path were there is a .ini and a path named "data files". In my case, the folder was named "datas", so never found it.

I suggest to let user be able to write himself the directory where are datas.

Anyway, thanks for your help and your great work, it's really a pleasure to play to this game on Android!

**Comment by licaon-kter** [comment]
It's better to keep the game folder structure

That being said, you can edit the config and put whatever path you wish.
