### ISSUE TITLE
Crash on "Loading content file Morrowind.esm"...

### ISSUE THREAD

**Issue by waltspublic** [xyzz/openmw-android#31]
Last log entry... Nightly builds 28 and 29... Galaxy J3 Orbit (Mali GPU)... Android 8.0.0... Vanilla GoG... 

Anyway, I've been enjoying this, immensely. I'll just go back to build 27, until the matter irons out.

**Comment by xyzz** [comment]
Can you please open the menu (three dots on top right) and make sure that crash reporting is enabled?

**Comment by waltspublic** [comment]
Sure, I'll do that. I already reverted to build 27 though, which never crashed. Nevertheless, I'll be sure to enable reporting going forward.

**Comment by xyzz** [comment]
Thanks, I do see the crash now.

**Comment by xyzz** [comment]
Fixed in the latest nightly
