### ISSUE TITLE
Beginning without intro

### ISSUE THREAD

**Issue by ciseur68** [xyzz/openmw-android#32]
Hi, first of all thanks for your huge work.
In 46.0.27 nightly, I have no introduction video when I run a new game, and nobody talks. I have the French version of the game, maybe the problem ?
Android 9, Samsung galaxy A6

**Comment by licaon-kter** [comment]
openmw.log ?

**Comment by ciseur68** [comment]
[openmw.log](https://github.com/xyzz/openmw-android/files/3797821/openmw.log)

**Comment by licaon-kter** [comment]
Do copy all Data Files from CD as the log says you're missing a lot of folders.

This is a GOTY (main game, Tribunal, Bloodmoon) install, right?

**Comment by ciseur68** [comment]
I got the files from the installed directory on my computer, some files are probably missing. I'll try to get those of the CD.

**Comment by xyzz** [comment]
That sounds like you didn't copy the proper files, these problems are better discussed on the forums, https://forum.openmw.org/viewtopic.php?f=47&t=5626
