### ISSUE TITLE
implement folder-selection for data folder

### ISSUE THREAD

**Issue by DrAzraelTod** [xyzz/openmw-android#34]
the var for local path where the game data is stored shouldn't be implemented as a simple text input, but via some dedicated file-selection-input

further the var produced should be escaped and stored in quotes, to allow things like "/storage/0000-0000/Morrowind/Data Files/" to work

this currently breaks, unless the user himself enters the var including quotes (the minimal effort "solution" would be to add a help-label that explains how to enter paths with spaces and other special chars)

**Comment by xyzz** [comment]
The file selection dialog was implemented back in May, please download a newer build from the releases page or Google Play.
