### ISSUE TITLE
ffmpeg fails to build

### ISSUE THREAD

**Issue by strikersix23** [xyzz/openmw-android#39]
An issue on ubuntu 18.0.4 

ffmpeg and its libs fails to compile with version mismatch I will upload a text log soon I might have a fix if it works I will send it along with the original error

**Comment by licaon-kter** [comment]
Maybe you don't have all the deps, eg. https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/is.xyz.omw_nightly.yml#L264

**Comment by strikersix23** [comment]
The only I didn't have was doxygen but that doesn't affect ffmpeg

**Comment by strikersix23** [comment]
Build fails still

**Comment by xyzz** [comment]
Log file?

**Comment by strikersix23** [comment]
Ill try to build on Tuesday. The original official openme compiles correctly I'm going to try again

**Comment by strikersix23** [comment]
here is the error

-- Found FFmpeg: /home/aj/openmw-android/buildscripts/prefix/arm/lib/libavcodec.a;/home/aj/openmw-android/buildscripts/prefix/arm/lib/libavformat.a;/home/aj/openmw-android/buildscripts/prefix/arm/lib/libavutil.a;/home/aj/openmw-android/buildscripts/prefix/arm/lib/libswscale.a;/home/aj/openmw-android/buildscripts/prefix/arm/lib/libswresample.a  found components:  AVCODEC AVFORMAT AVUTIL SWSCALE SWRESAMPLE
-- libavformat is too old! (, wanted 57.56.100)
-- libavcodec is too old! (, wanted 57.64.100)
-- libavutil is too old! (, wanted 55.34.100)
-- libswscale is too old! (, wanted 4.2.100)
-- libswresample is too old! (, wanted 2.3.100)
CMake Error at CMakeLists.txt:208 (message):
  FFmpeg version is too old, 3.2 is required


-- Configuring incomplete, errors occurred!
See also "/home/aj/openmw-android/buildscripts/build/arm/openmw-prefix/src/openmw-build/CMakeFiles/CMakeOutput.log".
make[2]: *** [openmw-prefix/src/openmw-stamp/openmw-configure] Error 1
make[1]: *** [CMakeFiles/openmw.dir/all] Error 2
make: *** [all] Error 2

**Comment by xyzz** [comment]
And what's in `/home/aj/openmw-android/buildscripts/build/arm/openmw-prefix/src/openmw-build/CMakeFiles/CMakeOutput.log`?

**Comment by strikersix23** [comment]
here
[CMakeOutput.log](https://github.com/xyzz/openmw-android/files/4335539/CMakeOutput.log)

**Comment by strikersix23** [comment]
anything wrong?

**Comment by xyzz** [comment]
Is it running on WSL? Try compiling it on a real Ubuntu 18.04 VM. The script at https://github.com/xyzz/openmw-android/blob/master/buildscripts/ssh-build.sh is what I use for clean 18.04 VMs on AWS, so it should always work.

**Comment by strikersix23** [comment]
Im using wsl2 with Ubuntu 18.04 running on wsl2 Linux kernel I've compiled on wsl before and it worked I tested vanilla openmw port and ffmpeg works fine

**Comment by strikersix23** [comment]
Can you tell me the deps that I need on the native system

**Comment by strikersix23** [comment]
Is htop and 7zip a hard dependency do I need qt5

**Comment by strikersix23** [comment]
I don't have acces to aws vm

**Comment by licaon-kter** [comment]
Works fine in a local Virtualbavox Debian VM with fdroidserver.

**Comment by Sisah2** [comment]
Does anyone find solution without using virtual machine?

**Comment by Sisah2** [comment]
Got it to work, removing "NOT" in line "if (NOT  WIN32)" in file buildscripts/build/arm64/openmw-prefix/src/openmw/CMakeLists.txt disable that check and compile fine, just search for ffmpeg in that file.
