### ISSUE TITLE
Gamma Slider?

### ISSUE THREAD

**Issue by merpysoup** [xyzz/openmw-android#45]
It is very hard to see in most of the game due to the lack of the gamma slider in the video settings. Many other video settings from morrowind are also missing that would be great to have.

**Comment by licaon-kter** [comment]
There's a gamma setting in the launcher, it doesn't work for you?

**Comment by merpysoup** [comment]
> There's a gamma setting in the launcher, it doesn't work for you?

There is none for me on both nightly and stable, unless it has been added since last month or two?

**Comment by licaon-kter** [comment]
0.46-34 from F-Droid has it...
