### ISSUE TITLE
A more modular approach to installing mods

### ISSUE THREAD

**Issue by snyman** [xyzz/openmw-android#46]
I'd like to add UI functionality that will allow the user to specify additional data file directories (basically extra `data=` entries in `openmw.cfg`). The benefit of this is that it allows installing/uninstalling/updating mods without worrying about conflicts with other mods or the base game.

Looking at the code, this won't be a trivial change as several parts of the existing mod management code assumes only a single data file directory. So I'm opening this issue as a way to get early feedback and guidance, and also to make sure this isn't already being worked on. Here are my tentative plans:

- Add a third tab to the "Mods" activity that will allow the user to add/remove/(enable/disable?)/reorder the extra data directories
- `DataDir` will be implemented as a third value for the `ModType` enum
- I will probably have to either add a database column or change the `filename` column to be a full path, to allow associating plugin/resource type mods with the data dir mods they come from
- And of course the `ModsCollection` will have to scan all the data dirs, as well as rescanning to update the list when a data dir is added or removed.

So, any questions, comments, or suggestions?

**Comment by xyzz** [comment]
My initial plan was to wait until a new openmw-specific mod format is implemented and see from there, however as it doesn't seem to be happening anytime soon, I think your approach is reasonable.
