### ISSUE TITLE
Game files selection crash on Android 11

### ISSUE THREAD

**Issue by dnllln** [xyzz/openmw-android#47]
On Android 11 (Pixel 3XL) there appears to be a persistent crash upon clicking Game files to set the path variable. I assume it's something not playing nice with the new Android versions menu dialogue. As soon as the menu option is clicked the app closes. 

I just thought y'all should be aware. Thank you!

**Comment by licaon-kter** [comment]
You've granted storage access always or on use?

**Comment by dnllln** [comment]
> You've granted storage access always or on use?

It's set to always. I just double checked.

**Comment by IISAKNIFE** [comment]
This is an issue for me to. Android 11, both Pixel 3a and Pixel 4a. Crashes as soon as I click on game files. All permissions are granted fully.

**Comment by dnllln** [comment]
Seems to be an issue with the storage-chooser library specific to Android 11. They haven't updated the library on their end yet.

**Comment by Nepoxx** [comment]
Is there a manual way to specify the location of game files in the meantime?

**Comment by licaon-kter** [comment]
I guess this is the continuation of https://github.com/xyzz/openmw-android/issues/30 ?

**Comment by xyzz** [comment]
This is the upstream bug - https://github.com/codekidX/storage-chooser/issues/127, I'm seeing the same backtrace in crash reports. Not sure why it's crashing though since we're targeting api 28.

**Comment by xyzz** [comment]
Could you try this build:

[omw_debug_0.47.0-37.zip](https://github.com/xyzz/openmw-android/files/5317032/omw_debug_0.47.0-37.zip)

**Comment by IISAKNIFE** [comment]
> Could you try this build:
> 
> [omw_debug_0.47.0-37.zip](https://github.com/xyzz/openmw-android/files/5317032/omw_debug_0.47.0-37.zip)
> 

This build works on my 4a on android 11

**Comment by dnllln** [comment]
> Could you try this build:
> 
> [omw_debug_0.47.0-37.zip](https://github.com/xyzz/openmw-android/files/5317032/omw_debug_0.47.0-37.zip)

Works for me as well on the 3 XL on Android 11. GLESv2 doesn't load the game for me, but GLESv1 does. Separate issue, but the file picker now works.

**Comment by xyzz** [comment]
fixed in latest stable and nightly builds
