### ISSUE TITLE
Is this hardcoding the CPU cores used?

### ISSUE THREAD

**Issue by licaon-kter** [xyzz/openmw-android#49]
...because in F-Droid at least we have more than 4: https://github.com/xyzz/openmw-android/blob/master/buildscripts/CMakeLists.txt#L86

Or am I misunderstanding its purpose?

**Comment by xyzz** [comment]
basically yes but that only applies to libraries using ndk-build: SDL2 and gl4es, both of which build pretty much instantly

**Comment by licaon-kter** [comment]
Great
