### ISSUE TITLE
ARM + LTO = error

### ISSUE THREAD

**Issue by licaon-kter** [xyzz/openmw-android#50]
For F-Droid, since compiling takes ages, I've tested only the ARM64 build.

But now on the build server the LTO build of nightly 37 fails:
```
[100%] Linking C shared library libopenal.so
/home/vagrant/build/is.xyz.omw_nightly/buildscripts/toolchain/ndk/toolchains/llvm/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld.gold: fatal error: Optimization level must be between 0 and 3
```

I'll reverse the LTO part so at least it builds but any idea on how to fix?

Ref: https://github.com/android/ndk/issues/721
Ref: https://reviews.llvm.org/D79919
Buildlog: [is.xyz.omw_nightly_37.log.gz](https://github.com/xyzz/openmw-android/files/5327952/is.xyz.omw_nightly_37.log.gz)

**Comment by xyzz** [comment]
it's because fdroid scripts aren't using our NDK which is carefully patched against this specific issue :) https://github.com/xyzz/openmw-android/blob/0eafab92a23e54a947f6fb303aaf18480d974ad1/buildscripts/include/setup-ndk.sh#L32-L33

**Comment by licaon-kter** [comment]
I'll steal that and you can't stop me! :)
