### ISSUE TITLE
Level up/skill up bug

### ISSUE THREAD

**Issue by zyrafadzagamanafa** [xyzz/openmw-android#51]
I ran into a bug related to level up/skill up in versions above 0.46.0.18

Every time I read a skill book i get audio notification (holy sound) without popup notification. I mean I can endlessly read one skills book, so I can grind skills/levels endlessly.

A similar situation occurs with manual skill up. When the skill progress reaches 100, skill does not raise, but the value grows over 100. For example I've reached 100/100 progress to level up skill and instead of advance, it's continues to progress above (xxx/100). And the same as with the skill book, I get only audio notification.

openmw.log says for every skill up 
Error in frame: basic_string

I'm using the clean version of Morrowind without mods. 
Device: Redmi 5 
Android: 8.1.0

**Comment by xyzz** [comment]
please attach your entire openmw.log

**Comment by zyrafadzagamanafa** [comment]
[openmw.log](https://github.com/xyzz/openmw-android/files/5348876/openmw.log)

for the test I used lastest nightly build 0.47.0-37-nightly 
Test process: I started a new game, went through the tutorial, went to Foryn Gilnith's Shack and read it 12 times, quicksave game and exit.

for the sake of clarity, I think I checked all or almost all of the versions available on the github and the last ones where I do not have this problem are 0.46.0.18 and below.

I hope my explanations will help you with something

**Comment by zyrafadzagamanafa** [comment]
It turns out that the issue is caused by graphic library GLESv2

**Comment by xyzz** [comment]
Ok, can you provide following additional information:

- full firmware version/build number
- a zipped copy of your `/storage/emulated/0/Morrowind` (don't post it here, email to omw@xyz.is)
- a list of settings configured within OMW which are different from defaults

**Comment by akortunov** [comment]
A related function is the `MWMechanics::NpcStats::increaseSkill`. If I understood correctly, it fails after playing the sound, when it tries to format or print a message box. Nothe that it can be the same issue as #48 since when you add an item via dialogue script, a message box about added item should be printed as well.

**Comment by xyzz** [comment]
No response from the reporter, cannot act on this issue.
