### ISSUE TITLE
Crash on save game (0.47.0-38-nightly)

### ISSUE THREAD

**Issue by waltspublic** [xyzz/openmw-android#52]
0.47.0-38-nightly is crashing on save game

Revert to prior nightly version displays none of this behavior

App installed via Play Store

Device model is Samsung Galaxy  A01 (SM-A01571)

**Comment by xyzz** [comment]
could you try latest nightly release version 39?

**Comment by waltspublic** [comment]
Sure, I'll give it another try.

**Comment by waltspublic** [comment]
Yep, that did it. Thanks.
