### ISSUE TITLE
Add gyroscopic aiming.

### ISSUE THREAD

**Issue by matj1** [xyzz/openmw-android#53]
The game could detect rotation of the device and use it to emulate mouse movement. It would make aiming easier in my opinion and allow using the finger for other things (jumping, attacking…) while aiming. In menus, it could be helpful when the analog stick sensitivity is high, so selecting small items with it is hard. Similar controls sam be seen in Delta Touch, Quad Touch and other Android games, in many Switch games, or by searching “gyro aiming” on YouTube.

**Comment by Merionis** [comment]
The Nintendo Switch does have this and it is a game changer, I think it would be great

**Comment by xyzz** [comment]
gyroscope aiming is supported since quite some time ago, https://github.com/OpenMW/openmw/blob/66c884be6515cd6e94a392dbad7e8267fdd7b2e2/files/settings-default.cfg#L475-L491, however UI to configure it is missing in the launcher currently

**Comment by matj1** [comment]
@xyzz, thanks for the information. I'd like to be able to edit it in the UI. There are many settings, gyroscopic aiming settings aren's so special. I think it would be helpful to have a way to edit `settings.cfg` as text in the OMW app.

An alternative helpful way of editing settings would be to bookmark or register certain settings from `settings.cfg` in the OMW app settings and be able to set them with gui elements. For example, i would bookmark `gyro horizontal sensitivity`, and then I would have a slider that would set the setting's value.

Is something like that plausible?
