### ISSUE TITLE
A few important notes before updating openmw

### ISSUE THREAD

**Issue by AbduSharif** [xyzz/openmw-android#58]
- The new movement solver fixes MR has been merged, and OpenMW now uses bullet double precision by default because it fixes alot of physics issues and it is required for that MR changes to work more effectively, so it's a good idea to enable double precision for architectures that support it.

- That MR makes OpenMW use simpler collision boxes by default so the android patch is no longer needed and it will cause builds to fail anyway so it's better removed.

- With that MR changes there's a bug with 15 physics FPS where corpses slide down, so it would be a good idea to remove that option, 30 physics FPS or more doesn't have that bug, and OpenMW PC is using 60 by default anyway.

And thanks for keeping this port alive.

**Comment by AbduSharif** [comment]
It's starts from this commit:
https://gitlab.com/OpenMW/openmw/-/commit/851a0245aca46602ff6266a1cef481723ebc6073

**Comment by xyzz** [comment]
ok all done in 655c91009f62a41f17a0b59f6f2cb78d2303f7e5
