### ISSUE TITLE
Validate custom OpenMW patches

### ISSUE THREAD

**Issue by akortunov** [xyzz/openmw-android#61]
Some [OpenMW patches](https://github.com/xyzz/openmw-android/tree/master/buildscripts/patches/openmw) may be not needed anymore, some may be implemented in a better way:

1. 0001 - it does not have any explanation why it is needed and I did not see any bugreports related to `setupCopyFramebufferToTextureCallback`.
2. 0002 - it is not used at all and can be removed.
3. 0003 - a related [data race](https://gitlab.com/OpenMW/openmw/-/issues/4844) is supposed to be [fixed](https://gitlab.com/OpenMW/openmw/-/commit/ab03b9ac1cee04f91cad0e6d5618242e0067d49a) now - savegame loading does not try to sort landscape since it is static for given session.
4. 0004 - the issue is [worked around](https://gitlab.com/OpenMW/openmw/-/merge_requests/557/diffs?commit_id=eb80c997b8255e86b86096bc4ac9218929eaeddd) from OpenMW side, so both patches (for OpenMW and OSG) should not be needed now. 
5. 0009 - in theory, it should not be needed in 0.47. If it is still needed, it would be nice to specify such cases - maybe it would be better to fix them on OpenMW side.
6. 0005 and 0013 - it would be better to discuss them with OpenMW developers. Probably OpenMW can define a new layer to define platform-specific default settings values (e.g. via `android-settings.cfg` config file).
7. 0014 - again, it is unclear why it is needed. An only case when setting changes are not saved to settings.cfg is when OpenMW process crashed or was terminated. Such cases should be very rare, otherwise they need investigation rather than hacks.

**Comment by xyzz** [comment]
0001 - this created a flash of white screen (or iirc just solid white screen?) when loading new area
0014 - usually people on Android close the app by swiping it off the drawer, in which case the save code wasn't triggered. As well, if the app is backgrounded and then gets killed due to e.g. low memory, it was not triggered.

**Comment by akortunov** [comment]
> usually people on Android close the app by swiping it off the drawer, in which case the save code wasn't triggered.

In this case OS should provide application a way to quit gracefully rather than silently kill it without proper cleanup. I'd suggest to investigate [SDL_APP_TERMINATING event](https://wiki.libsdl.org/SDL_EventType#Android.2C_iOS_and_WinRT_Events) and [onTaskRemoved and onStop methods](https://stackoverflow.com/questions/19568315/how-to-handle-code-when-app-is-killed-by-swiping-in-android).

> this created a flash of white screen (or iirc just solid white screen?) when loading new area

At least, it should be documented in the patch description, but better to investigate it - it may be an OpenMW, OSG or GL4ES bug. BTW, there was a [similar regression](https://gitlab.com/OpenMW/openmw/-/merge_requests/472#note_469647915), so the root of the issue may be the same.

**Comment by AbduSharif** [comment]
This merged now, I still use the OSG patch because the game freezes alot without it:
https://gitlab.com/OpenMW/openmw/-/merge_requests/557/diffs?commit_id=eb80c997b8255e86b86096bc4ac9218929eaeddd

**Comment by akortunov** [comment]
I see two possibilities here:
1. There is an use-case, which was not reported by xyzz
2. OSG patch just gives you a placebo effect.

**Comment by AbduSharif** [comment]
It might be the second thing, I disabled the OSG patch for a new build and explored the game for a while, I still have a few freezes but it's still alot less than the first time I tested without it.

**Comment by AbduSharif** [comment]
I found out the additional reason for for game freezes, on my devices there's a couple of graphics drivers, it was a matter of switching back the graphics driver and never miss with it again.

**Comment by docent27** [comment]
I built the APK by disabling all patches except number 10 (for some reason it caused an error during the build, until I figured out why), the game works without problems. Are these patches really needed?

**Comment by xyzz** [comment]
> 0001-loadingscreen-disable-for-now.patch

Tested, the flash of white screen issue still occurs.

> 0002-scenemanager-disable-state-share-inc-compile.patch

removed

> 0003-globalmap-fix-race-vs-savegame-load.patch

removed

> 0004-getUVBuffer-pre-set-array-binding-to-avoid-thread-ra.patch
> 0003-Array-make-possible-to-use-thread-safely-with-setTex.patch

both removed

> 0009-windowmanagerimp-always-show-mouse-when-possible-pat.patch

Tested without the patch and there's no mouse in the main menu unless mouse is moved with the joystick, keeping the patch for now.

> 0005-android-Revert-UI-dimensions.patch
> 0013-android-Update-default-settings-for-android.patch

keeping both until openmw implements the aforementioned platform-specific config feature

> 0014-settingswindow-save-user-settings-file-when-ok-is-pr.patch

Also keeping this one unless somebody implements the version using SDL_APP_TERMINATING, I don't really have time or willingness to work on that.

---

Believe this should take care of everything so I'm closing this issue, feel free to open more specific issues if you wish.

**Comment by akortunov** [comment]
> Tested without the patch and there's no mouse in the main menu unless mouse is moved with the joystick

Are you sure? On PC mouse cursor appears in the main menu just after intro video.

**Comment by akortunov** [comment]
Also did you try to init `mCursorActive` field to `true` in the `WindowManager` constructor?

**Comment by xyzz** [comment]
> Are you sure?

yep

> Also did you try to init mCursorActive field to true in the WindowManager constructor?

No I haven't tried.
