### ISSUE TITLE
Grass instancing

### ISSUE THREAD

**Issue by pulion** [xyzz/openmw-android#64]
xyzz, please add grass instancing to your future builds.

**Comment by xyzz** [comment]
not sure what does that mean? Is there a configuration option?

**Comment by pulion** [comment]
> not sure what does that mean? Is there a configuration option?

https://github.com/OpenMW/openmw/pull/3023

**Comment by docent27** [comment]
This herb has long been merged into the master branch. The problem now is that it is impossible to build the APK on a fresh commit without errors in the log file.

**Comment by xyzz** [comment]
if it was merged then it will be added to the next build. No need to open an issue about it.

**Comment by Sisah2** [comment]
I know its closed, but best would be revert grass instancing and merge grass paging by akortunov, it work much much faster on android, because gl4es dont support instancing properly, it only emulating it.

https://github.com/akortunov/openmw/tree/grass_paging

Would it be possible to revert it automatically and merge paging throught buildscripts?

**Comment by docent27** [comment]
I have no difficulty with the grass that is currently in the MASTER branch.

**Comment by Sisah2** [comment]
It work without visual bugs, but main reason why it was made is improve performance, which it dont do (it run slower than loading grass as regular mod) but paging is basicaly the same and also improve performance a lot.

**Comment by pulion** [comment]
when comparing an APK file with grass instancing versus grass paging support, there really was a difference in favor of grass paging.  I don’t feel the difference now.  perhaps this is due to the capabilities of the new smartphone.  but I would gladly do again comparative tests on new APK files with the same settings, if there was such a possibility.

**Comment by Sisah2** [comment]
Well, there is huge difference.

**Comment by Sisah2** [comment]
Its simple. Instancing.
![Screenshot_20210228-150828_OMW Nightly](https://user-images.githubusercontent.com/64099446/109421332-18723700-79d7-11eb-85d4-9b5f6b07288e.jpg)
Paging
![Screenshot_20210228-150908_OMW (Debug)](https://user-images.githubusercontent.com/64099446/109421349-2922ad00-79d7-11eb-8d3f-6c12098ddb25.jpg)

**Comment by xyzz** [comment]
> Would it be possible to revert it automatically and merge paging throught buildscripts?

It's too much work for me to maintain such a large patch, if there are performance issues you should bring them up with openmw team and get it fixed in openmw master.
