### ISSUE TITLE
English and Russian keyboard switch.

### ISSUE THREAD

**Issue by docent27** [xyzz/openmw-android#67]
I really want to be able to switch the keyboard in the game from English to Russian. There are a lot of morrowind players from the former CIS countries.

**Comment by pulion** [comment]
I agree with the author of the request.  it would be nice to add a Russian-language keyboard layout to OpenMB.  A huge number of Russian-speaking players play in your project.  many want to call their nonrevarin a Russian name.  and the names of the potions created would also be nice to name in their own language.  Moreover, such an implementation has already been previously implemented in your APK file by the respected terrabit25.

**Comment by docent27** [comment]
Not relevant. I implemented this functionality myself.
