### ISSUE TITLE
Bugs with Gravius ​​and skills 

### ISSUE THREAD

**Issue by HACK-87** [xyzz/openmw-android#68]
Hello. There are 2 problems in newer versions of openmw since 0.46 

1. After leaving the ship, in Seyda Nin's concession, Cellus Gravius ​​does not leave the office. When you start a dialogue with him, a message does not appear that the documents have been transferred, and the entry in the diary is not updated. 
The script does not work, during the repeated dialogue, Gravius ​​says: "Who are you, where are your documents?" 
Documents from the inventory disappear, so you cannot leave the office. This problem was observed in openmw from the Google Play Market, in versions 0.46 and 0.47 

In the logs, he writes the following error:

Loading cell Seyda Neen, Census and Excise Office 
Dialogue error: An exception has been thrown: basic_string 
Dialogue error: An exception has been thrown: basic_string 

This problem was observed not only on my device, but also among other users.

2. In versions where there is a bug with Gravius, there are also bugs with obtaining skills. 
If you load a working save, play for a while, a bug appears. 
For example, the athletics skill should increase, when you jump, music plays about getting the skill, but nothing happens. The message about obtaining the skill is also not shown. 
A sound is heard with each jump, the skill is not counted. If after this you save the game and re-enter, then the bug will still make itself felt. The only solution is to load the previous save. But it helps until the next bug. 
Tested on GLESv2
This problem occurs with the Russified version of Morrowind, with any assembly.

Device: Lenovo A5
OS: Android 8.1
Version: 0.46 - 0.47 (nightly & stable)
App source: Google Play, github

**Comment by licaon-kter** [comment]
Mods or clean?

**Comment by HACK-87** [comment]
> Mods or clean?

And with mods and without.

**Comment by xyzz** [comment]
Please provide the following additional information:

- your device manufacturer and model (in this case include the full model number, i.e. L18021/L18081/L18011)
- full firmware version including the build number
- a zipped copy of your `/storage/emulated/0/Morrowind` (don't post it here, instead email it to omw@xyz.is)
- a list of settings configured within OMW which are different from defaults

**Comment by HACK-87** [comment]
Lenovo A5 
model: L18011 
Kernel version: 4.4.95+ 
Build number: 
[SW VERSION] 011019 release-keys 
[HW VERSION] 
VER.A 
Android version: 8.1.0

Link to settings.cfg

https://yadi.sk/d/bzLRjt5TW5Dt1A

**Comment by HACK-87** [comment]
https://github.com/xyzz/openmw-android/releases/download/2019-05-01/app-debug.apk

This version does not have a bug on any build. This is an old debug, but it works. All versions above have a problem with Gravius.

**Comment by xyzz** [comment]
https://github.com/xyzz/openmw-android/issues/48#issuecomment-784357930

**Comment by xyzz** [comment]
Please move all further discussion to https://github.com/xyzz/openmw-android/issues/48
