### ISSUE TITLE
Import saves from pc

### ISSUE THREAD

**Issue by Tidominer** [xyzz/openmw-android#70]
I've installed OpenMW on my android phone, then copied my pc game files from my computer. Now I can run the game but I can't find my saves. I also copied Saves folder but they're not in game.
I found openmw saves folder. but it looks the save files extension is .omwsave . I tried to rename .ess save to that format but didn't work.
Is there any way to use pc saves in android?

**Comment by docent27** [comment]
If you are playing the original morrowind on a PC, then the morrowind is not compatible with openmw.  The PC should have exactly the same version of openmw as on the phone, then the maturations will be compatible with each other.

**Comment by xyzz** [comment]
That is correct. Morrowind saves aren't compatible, only OpenMW.
