### ISSUE TITLE
OpenMW for Android status

### ISSUE THREAD

**Issue by licaon-kter** [xyzz/openmw-android#80]
...has changed and this version is now the official one?

The Github repo (https://github.com/OpenMW/android-port) is gone and the Gitlab one (https://gitlab.com/OpenMW/openmw-android) is a mirror of this repo.

**Comment by AbduSharif** [comment]
OpenMW android port isn't official.

**Comment by licaon-kter** [comment]
Are we lost in translation?

**Comment by AbduSharif** [comment]
Again OpenMW android port isn't official, this repo is the main OpenMW android repo.

**Comment by licaon-kter** [comment]
The old one wasn't official either?

**Comment by AbduSharif** [comment]
Yes, anyway have a read:
https://wiki.openmw.org/index.php?title=Bethesda_Emails

**Comment by xyzz** [comment]
As far as I'm aware, it's not an official project. I don't know why it's set up as a mirror, you should ask openmw team.

**Comment by licaon-kter** [comment]
@AbduSharif read them before merging the very first build on F-Droid.

So I guess the non-PCs will always be "not official' so as the OpenMW Team, and the whole project, be safe. 

Got it :)
