### ISSUE TITLE
Some notes before updating OpenMW

### ISSUE THREAD

**Issue by AbduSharif** [xyzz/openmw-android#88]
There has been alot of changes to OpenMW since the last update and it seems it broke some patches including:
https://github.com/xyzz/openmw-android/blob/master/buildscripts/patches/openmw/0014-settingswindow-save-user-settings-file-when-ok-is-pr.patch

(As of 4 days ago the patch was updated)

Also this feature has been introduced:
https://gitlab.com/OpenMW/openmw/-/issues/5500
It also solves some issues where nav mesh generation wasn't fast enough to cover areas around the player on Android devices (mostly) and that made some issues appear like:
https://gitlab.com/OpenMW/openmw/-/issues/5573

But as a trade off of the feature, loading screens might take a long time on those devices so it was suggested to change "max tiles number =" value to 50 in the settings-default.cfg patch as a workaround, this comment shows how it helps:
https://gitlab.com/OpenMW/openmw/-/merge_requests/819#note_568285548

**Comment by AbduSharif** [comment]
The feature has been merged to the OpenMW master branch:
https://gitlab.com/OpenMW/openmw/-/commit/fd89582e0ce20523e6c3f96a96540c3ec8526b2a

**Comment by xyzz** [comment]
the patch was updated 4 days ago, is it still broken?

**Comment by AbduSharif** [comment]
Oh I haven't tried that actually.

**Comment by AbduSharif** [comment]
It's not broken with latest master.

**Comment by AbduSharif** [comment]
It seems this also speed it up some more:
```
wait until min distance to player = 1
```

**Comment by Sisah2** [comment]
Seems like there is crash when using cyrilic encoding and clicking on options in journal when using sdk21

**Comment by xyzz** [comment]
see https://github.com/xyzz/openmw-android/issues/89#issuecomment-841670541 re: the last comment

**Comment by AbduSharif** [comment]
So it turn out most of the waiting time was a bug, fixes in:
https://gitlab.com/OpenMW/openmw/-/merge_requests/861

**Comment by AbduSharif** [comment]
It's now recommend to use "wait until min distance to player = " 3 or 4.

Still reducing "max tiles number = " value to something like 256 should help performance on Android devices especially when using a heavily modded setup in my testing.

**Comment by AbduSharif** [comment]
This MR (which has been merged recently) also broke how OpenMW android handles settings-default.cfg:
https://gitlab.com/OpenMW/openmw/-/merge_requests/822

**Comment by xyzz** [comment]
should all be resolved
