### ISSUE TITLE
NDK21 - game journal crashes.

### ISSUE THREAD

**Issue by docent27** [xyzz/openmw-android#89]
If you collect APK on NDK version 21 - the game crashes in the magazine (I attach a video file of the departure). This happens only in Russian encoding.

I found a solution to the problem, I took NDK20 as a basis and integrated the latest CLANG version from the NDK21 version there, in which case the APK is fully working. But I think this method is not correct, although it is working.

https://www.youtube.com/watch?v=zKoJevP_6Gc

**Comment by xyzz** [comment]
It's a bug in openmw, I've sent them a patch in https://github.com/OpenMW/openmw/pull/3089

**Comment by AbduSharif** [comment]
PR was merged :)

**Comment by docent27** [comment]
The problem is resolved. Now I can use the regular version of NDK21 and everything works. Thank you! I close this, the problem is resolved.
